### PR TITLE
Support capability system.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Comment by AlanDThiessen** [comment]
I've reviewed the changes, and they look ok.  Unfortunately, my CM11 device died in a recent power outage, and I no longer have the ability to test this with real hardware.  I can go ahead and merge it, and assume someone will open a defect if there are any troubles.  :-)

**Comment by mrstegeman** [comment]
Yikes! This should be safe to merge, and would be really helpful for our upcoming gateway release.

**Comment by mrstegeman** [comment]
@AlanDThiessen Thanks for merging! Would you mind cutting a new release soon?

**Comment by AlanDThiessen** [comment]
Sorry it took so long for me to get to this.  I'll see about doing a new release soon.  Is there any updated information/documentation on how to do a new release?  I seem to remember you moved the host site to Mozilla's S3 bucket.  How does that play into making a release?

**Comment by mrstegeman** [comment]
You can still just build the linux-arm/linux-x64/darwin-x64 packages as normal and host them as a release on your repository, then submit a PR or issue to the [addon-list repository](https://github.com/mozilla-iot/addon-list). I simply copy the packages into our S3 bucket and change the URLs.

**Pull request merged**
