### PR TITLE
Add cross-compile release workflow.

### PR DESCRIPTION
**Pull request by mrstegeman**
When you push a new tag named `vX.Y.Z`, this will automatically
cross-compile the add-on for all of the supported platforms. This
will allow the release to be handled automatically, rather than
building things manually via WebThingsIO/addon-builder.

### CODE REVIEW

**Comment by mrstegeman** [comment]
@AlanDThiessen would you mind merging this and tagging a new release? I'm trying to get everyone off of the addon-builder repo and the packages out of S3 as quickly as possible.

**Comment by AlanDThiessen** [comment]
Sure, I'll try to do it this evening.

**Review by AlanDThiessen — APPROVED** [review]

**Comment by mrstegeman** [comment]
@AlanDThiessen any luck?

**Comment by AlanDThiessen** [comment]
I'm sorry, I missed the "...and tag a new release" detail when I merged the pull request.  Is that all I have to do?

**Comment by mrstegeman** [comment]
Yep, that should be all you need to do.

**Comment by mrstegeman** [comment]
Also, don’t forget to update the version string in both package.json and manifest.json.

**Pull request merged**
