### PR TITLE
Updates for gateway 0.10.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Comment by AlanDThiessen** [comment]
Since initially developing this addon, I have not kept up with the status of the addon framework.  What is the best way to stay up-to-date with the changes?

**Comment by mrstegeman** [comment]
> Since initially developing this addon, I have not kept up with the status of the addon framework. What is the best way to stay up-to-date with the changes?

There haven't been any breaking changes (outside of manifest.json), only new additions. If you want to keep up with new changes, you could just watch [this repo](https://github.com/mozilla-iot/gateway-addon-node/).

As for 0.10+, this change should be all you need. If you update the `cm11a-js` dependency, we should be good to go for Node 10 and 12 (I'm hoping we can switch to 12 soon). I'd be happy to add this repo to our addon-builder and run it through the cross-compilation matrix for you.

EDIT: It looks like you already updated that dependency. :smiley:

**Comment by AlanDThiessen** [comment]
Adding the repo to the addon-builder would be great!  If I understand correctly, does the builder automatically build, test, and release the addon?

**Comment by mrstegeman** [comment]
The builder just cross-compiles for different platforms and Node versions. We then do a separate PR to actually update the addon-list repo.

**Comment by mrstegeman** [comment]
Let me know when you're ready for a release and I'll kick off the build process.

**Comment by AlanDThiessen** [comment]
Thank you, I think it's ready now.  I have some functionality I'd like to add, but that will be sometime in the future.  Thank you!

**Comment by mrstegeman** [comment]
Ok, I tried to run the builder but ran into a couple issues. #5 should fix things.

**Pull request merged**
